### ISSUE TITLE
How to mine using Bitcoin-cli like command?

### ISSUE THREAD

**Issue by zydjohnHotmail** [marcosmartinez7/geth-regtest#2]
Hello:
I have learned some Bitcoin core command line in Regtest.
In Regtest, you can create a wallet, and use it to mine or generate a lot of blocks. Like the following commands:
# bitcoin-cli createwallet "Miner"
# bitcoin-cli -rpcwallet=Miner -generate 101
Then use the following command to see the wallet balance:
#bitcoin# bitcoin-cli -rpcwallet=Miner getbalance

But I have no experienc with geth, I don't know if geth has such mining or generate 100+ blocks to get some rewards in BTC?
I want to know if I use this repo, how can I generate or mine some ETH, so I can send to others without using any testnet faucet.
Please advise,
Thanks,

**Comment by marcosmartinez7** [comment]
Hi @zydjohnHotmail 

> But I have no experienc with geth, I don't know if geth has such mining or generate 100+ blocks to get some rewards in BTC?
 

First of all Geth is Ethereum based, you won't receive BTC, you will receive ETH if that's the case

> I want to know if I use this repo, how can I generate or mine some ETH, so I can send to others without using any testnet faucet.

Yes, you totally can. By creating a private regtest network you have control of the preallocated accounts. Those accounts have funds from the genesis block (block zero) 

How do you modify the accounts that will have pre allocated ETH? by adding an entry on the `alloc` array at the [regtest-low-dif.json](https://github.com/marcosmartinez7/geth-regtest/blob/master/regtest-low-dif.json#L20) 

Please take a look at the last account: 

``` 
"1c21a4bc096377a1b80d180ca7bad712062677ae": {
      "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
    }

``` 

You can place there an account that you know the private key. For example, you can use vanity-eth to generate an account (https://vanity-eth.tk)  and then place it there 

``` 
"0xD8EB2a7AcBf51240A64B56202816Af6aF5d3a7bD": {
  "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
}

```

This JSON is used as a genesis file and has all the configurations for your private network

With the control of the private key of the preallocated account you can send to another wallets easily: 
a) use Metamask, connect to localhost (your geth node) and send ETH to another account
b) connect hardhat or truffle to localhost (your geth node) and send ETH using web3.js or ethers 

Hope it helps, otherwise let me know

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your quick and detailed instructions. I have yet another question: I want to use CURL to send json RPC requests to Geth for the following actions: 
1) get account balance, 
2) create a new wallet with ERC20 format address, 
3) transfer some ETH from one preallocated account to the new accout just created.
In BTC regtest net, I can easily do this via bitcoin-cli, and I have successfully done the job via CURL commands using docker image on my Windows 10 PC.
What are the corresponding commands from GETH for the above 3 types of actions?
What are the corresponding json RPC payload for using CURL to do the job?
Please advise,
Thanks,

**Comment by marcosmartinez7** [comment]
Glad you find it useful. 

The Ethereum documentation has a detailed API explanation with curl examples. You can find it here: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getbalance

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I looked at the documents, it seems almost the same as BTC RPC calls, then it will be easy for me to do.
Thanks for your help, if I have more questions, I will raise an issue again!
